version: '3.1'

services:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-config/import:/opt/keycloak/data/import:ro
      - ./keycloak-config/export:/opt/keycloak/data/export:wo
    ports:
      - "8080:8080"
    command: -v start-dev --import-realm

  postgres:
    container_name: database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    ports:
      - '5432:5432'

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    depends_on:
      - postgres
    command:
      - --changelog-file=./src/main/resources/db/changelog/db.changelog-master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://localhost:5432/postgres
      - --username=username
      - --password=password
      - update
