spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tasks-manager
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs

app-config:
  keycloakTokenUrl: http://localhost:8080/realms/tasks-manager/protocol/openid-connect/token
